In [1]:
!pip install gensim

Requirement already satisfied: gensim in /usr/local/lib/python3.10/dist-packages (4.3.3)
Requirement already satisfied: numpy<2.0,>=1.18.5 in /usr/local/lib/python3.10/dist-packages (from gensim) (1.26.4)
Requirement already satisfied: scipy<1.14.0,>=1.7.0 in /usr/local/lib/python3.10/dist-packages (from gensim) (1.13.1)
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.10/dist-packages (from gensim) (7.0.5)
Requirement already satisfied: wrapt in /usr/local/lib/python3.10/dist-packages (from smart-open>=1.8.1->gensim) (1.16.0)

In [140]:
import gensim
from gensim.models import word2vec, KeyedVectors

In [141]:
import pandas as pd
messages = pd.read_csv("/content/SMSSpamCollection.txt", sep='\t', names=["label","message"])

In [142]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [143]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [144]:
import re
corpus = []
for i in range(0,len(messages)):
    review = re.sub('[^a-zA-Z]', '  ',messages['message'][i])
    review = review.lower()
    review= review.split()
    review = [lemmatizer.lemmatize(word) for word in review]
    review = ' '.join(review)
    corpus.append(review)
    print(review)

Streaming output truncated to the last 5000 lines.
do you know where my lab goggles went
can you open the door
waiting for your call
nope i waiting in sch daddy
you have won cash or a prize to claim call
i m tired of arguing with you about this week after week do what you want and from now on i ll do the same
wait me in sch i finish ard
our mobile number ha won to claim call u back or ring the claim hot line on
arngd marriage is while u r walkin unfortuntly a snake bite u bt love marriage is dancing in frnt of d snake amp sayin bite me bite me
huh so early then having dinner outside izzit
ok anyway no need to change with what you said
we tried to contact you re your reply to our offer of min textand a new video phone call now or reply for free delivery tomorrow
my ex wife wa not able to have kid do you want kid one day
so how s scotland hope you are not over showing your jjc tendency take care live the dream
tell them u have a headache and just want to use hour of sick time
i dun thk i ll quit yet hmmm can go jazz yogasana oso can we can go meet em after our lesson den
pete can you please ring meive hardly gotany credit
ya srsly better than yi tho
i m in a meeting call me later at
for ur chance to win a wkly shopping spree txt shop to t s c s www txt shop com custcare x p wk
you have been specially selected to receive a pound award call before the line close cost ppm t c apply ag promo
private your account statement for show un redeemed s i m point call identifier code expires
you still at grand prix
i met you a a stranger and choose you a my friend a long a the world stand our friendship never end let be friend forever gud nitz
i am great how are you
gud mrng dear have a nice day
you have an important customer service announcement call freephone now
will do wa exhausted on train this morning too much wine and pie you sleep well too
i m going out to buy mum s present ar
mind blastin no more tsunami will occur from now on rajnikant stopped swimming in indian ocean d
if u sending her home first it s ok lor i m not ready yet
speaking of doe he have any cash yet
be happy there i will come after noon
meet after lunch la
take care n get well soon
xclusive clubsaisai morow soiree speciale zouk with nichols from paris free rose all lady info
what i meant to say is cant wait to see u again getting bored of this bridgwater banter
neva mind it s ok
it s fine imma get a drink or somethin want me to come find you
day to kick off for euro u will be kept up to date with the latest news and result daily to be removed send get txt stop to
it a valentine game send dis msg to all ur friend if answer r d same then someone really love u ques which colour suit me the best rply me
i have many dependent
thanx today cer it wa nice catch up but we ave find more time more often oh well take care c u soon c
i called and said all to him then he have to choose this future
happy valentine day i know it early but i have hundred of handsomes and beauty to wish so i thought to finish off aunty and uncle st
he like not v shock leh co telling shuhui is like telling leona also like dat almost all know liao he got ask me abt ur reaction lor
for my family happiness
i come n pick up come out immediately aft ur lesson
let there be snow let there be snow this kind of weather brings ppl together so friendship can grow
dear we got lt gt dollar hi hi
good word but word may leave u in dismay many time
make sure alex know his birthday is over in fifteen minute a far a you re concerned
sorry no have got few thing to do may be in pub later
nah it s straight if you can just bring bud or drink or something that s actually a little more useful than straight cash
haha good to hear i m officially paid and on the market for an th
how many lick doe it take to get to the center of a tootsie pop
yup i thk they r e teacher said that will make my face look longer darren ask me not cut too short
new textbuddy chat horny guy in ur area just p free receive search postcode or at gaytextbuddy com txt one name to
today vodafone number ending with are selected to a receive a award if your number match call to receive your award
please dont say like that hi hi hi
thank u
oh that wa a forwarded message i thought you send that to me
got it seventeen pound for seven hundred ml hope ok
dear voucher holder claim this week offer at your pc go to http www e tlp co uk expressoffer t c apply stop text txt stop to
me n him so funny
sweetheart hope you are not having that kind of day have one with load of reason to smile biola
when login dat time dad fetching home now
what will we do in the shower baby
i had askd u a question some hour before it answer
well imma definitely need to restock before thanksgiving i ll let you know when i m out
said kiss kiss i can t do the sound effect he is a gorgeous man isn t he kind of person who need a smile to brighten his day
probably gonna swing by in a wee bit
ya very nice be ready on thursday
allo we have braved the bus and taken on the train and triumphed i mean we re in b ham have a jolly good rest of week
watching cartoon listening music amp at eve had to go temple amp church what about u
do you mind if i ask what happened you dont have to say if it is uncomfortable
private your account statement for show un redeemed s i m point call identifier code expires
no prob i will send to your email
you have won cash or a prize to claim call t c rstm sw s ppm
thats cool sometimes slow and gentle sonetimes rough and hard
i m gonna say no sorry i would but a normal am starting to panic about time sorry again are you seeing on tuesday
wait do you know if wesley in town i bet she doe hella drug
fine i miss you very much
did u got that person story
tell them the drug dealer s getting impatient
sun cant come to earth but send luv a ray cloud cant come to river but send luv a rain i cant come to meet u but can send my care a msg to u gud evng
you will be in the place of that man
it doesnt make sense to take it there unless it free if you need to know more wikipedia com
and are premium phone service call
under the sea there lay a rock in the rock there is an envelope in the envelope there is a paper on the paper there are word
then mum s repent how
sorry me going home first daddy come fetch later
leave it de start prepare for next
yes baby we can study all the position of the kama sutra
en chikku nange bakra msg kalstiya then had tea coffee
carlos ll be here in a minute if you still need to buy
this pay is lt decimal gt lakh
have a good evening ttyl
did u receive my msg
ho ho big belly laugh see ya tomo
sm ac sun post hello you seem cool wanted to say hi hi stop send stop to
get ur st ringtone free now reply to this msg with tone gr top tone to your phone every week just per wk opt out send stop
ditto and you won t have to worry about me saying anything to you anymore like i said last night you do whatever you want and i ll do the same peace
i ve got lt gt any way i could pick up
i dont knw pa i just drink milk
maybe say hi to and find out if got his card great escape or wetherspoons
piggy r u awake i bet u re still sleeping i m going lunch now
cause i m not freaky lol
missed your call cause i wa yelling at scrappy miss u can t wait for u to come home i m so lonely today
what is this hex place you talk of explain
log off wat it s sdryb i
is xy going e lunch
hi i m sue i am year old and work a a lapdancer i love sex text me live i m i my bedroom now text sue to by textoperator g da ppmsg
i wanted to ask to wait me to finish lect co my lect finish in an hour anyway
have you finished work yet
every king wa once a cry baby and every great building wa once a map not imprtant where u r today but where u wil reach tomorw gud ni
dear me at cherthala in case u r coming cochin pls call bfore u start i shall also reach accordingly or tell me which day u r coming tmorow i am engaged an it holiday
thanks love but am i doing torch or bold
forwarded from please call immediately a there is an urgent message waiting for you
wa the farm open
sorry to trouble u again can buy d for my dad again all big small sat n sun thanx
my sister in law hope you are having a great month just saying hey abiola
will purchase d stuff today and mail to you do you have a po box number
ah poop look like ill prob have to send in my laptop to get fixed cuz it ha a gpu problem
good good job i like entrepreneur
aight you close by or still down around alex s place
meet you in corporation st outside gap you can see how my mind is working
mum ask to buy food home
k u also dont msg or reply to his msg
how much r willing to pay
sorry i ll call later
what is important is that you prevent dehydration by giving her enough fluid
thats a bit weird even where is the do supposed to be happening but good idea sure they will be in pub
true dear i sat to pray evening and felt so so i sm d you in some time
i don t think i can get away for a trek that long with family in town sorry
so when do you wanna gym harri
quite late lar ard anyway i wun b drivin
to review and keep the fantastic nokia n gage game deck with club nokia go www cnupdates com newsletter unsubscribe from alert reply with the word out
mths half price orange line rental latest camera phone free had your phone mths call mobilesdirect free on to update now or stoptxt t c
height of confidence all the aeronautics professor wer calld amp they wer askd sit in an aeroplane aftr they sat they wer told dat the plane w made by their student dey all hurried out of d plane bt only didnt move he said if it is made by my student this wont even start datz confidence
it just seems like weird timing that the night that all you and g want is for me to come smoke is the same day a when a shitstorm is attributed to me always coming over and making everyone smoke
between am pm cost p
save yourself the stress if the person ha a dorm account just send your account detail and the money will be sent to you
he also know about lunch menu only da i know
when i have stuff to sell i ll tell you
urgent this is the nd attempt to contact u u have won call b t csbcm wc n xx callcost ppm mobilesvary max
book which lesson then you msg me i will call up after work or sth i m going to get spec my membership is px
you have won a guaranteed cash or a prize to claim yr prize call our customer service representative on between am pm
macha dont feel upset i can assume your mindset believe me one evening with me and i have some wonderful plan for both of u let life begin again call me anytime
oh is it send me the address
s fine anytime all the best with it
that is wondar full flim
ya even those cooky have jelly on them
the world is running and i am still maybe all are feeling the same so be it or i have to admit i am mad then where is the correction or let me call this is life and keep running with the world may be u r also running let run
got it it look scrumptious daddy want to eat you all night long
of co can lar i m not so ba dao ok pm lor y u never ask where we go ah i said u would ask on fri but he said u will ask today
alright omw gotta change my order to a half th
exactly anyways how far is jide her to study or just visiting
dunno y u ask me
email alertfrom jeri stewartsize kbsubject low cost prescripiton drvgsto listen to email call
no he didn t spring is coming early yay
lol you won t feel bad when i use her money to take you out to a steak dinner d
even u dont get in trouble while convincing just tel him once or twice and just tel neglect his msg dont c and read it just dont reply
leaving to qatar tonite in search of an opportunity all went fast pls add me in ur prayer dear rakhesh
then why no one talking to me
thanks for looking out for me i really appreciate
hi customer loyalty offer the new nokia mobile from only at txtauction txt word start to no get yours now t ctxt tc p mtmsg
wish i were with you now
haha mayb u re rite u know me well da feeling of being liked by someone is gd lor u faster go find one then all gal in our group attached liao
yes i will be there glad you made it
do well all will for little time thing of good time ahead
just got up have to be out of the room very soon i hadn t put the clock back til at i shouted at everyone to get up and then realised it wa wahay another hour in bed
ok there may be a free gym about
men like shorter lady gaze up into his eye
dunno he jus say go lido same time
i promise to take good care of you princess i have to run now please send pic when you get a chance ttyl
u are subscribed to the best mobile content service in the uk for per day until you send stop to helpline
is there a reason we ve not spoken this year anyways have a great week and all the best in your exam
by monday next week give me the full gist
do you realize that in about year we ll have thousand of old lady running around with tattoo
you have an important customer service announcement from premier
dont gimme that lip caveboy
when did you get to the library
realy sorry i don t recognise this number and am now confused who r u please
so why didnt you holla
cant think of anyone with spare room off top of my head
faith make thing possible hope make thing work love make thing beautiful may you have all three this christmas merry christmas
u should have made an appointment
call me when you carlos is are here my phone s vibrate is acting up and i might not hear text
romantic paris night flight from book now next year call t c apply
we are at grandma oh dear u still ill i felt shit this morning but i think i am just hungover another night then we leave on sat
urgent ur guaranteed award is still unclaimed call now closingdate claimcode m m pmmorefrommobile bremoved mobypobox l yf
nothing but we jus tot u would ask co u ba gua but we went mt faber yest yest jus went out already mah so today not going out jus call lor
wishing you and your family merry x ma and happy new year in advance
ur awarded a city break and could win a summer shopping spree every wk txt store to skilgme tscs winawk age perwksub
i m nt goin got somethin on unless they meetin dinner lor haha i wonder who will go ti time
sorry i ll call later
i cant pick the phone right now pls send a message
lol i know they re so dramatic school already closed for tomorrow apparently we can t drive in the inch of snow were supposed to get
not getting anywhere with this damn job hunting over here
lol u drunkard just doing my hair at d moment yeah still up tonight wats the plan
idc get over here you are not weaseling your way out of this shit twice in a row
i wil be there with in lt gt minute got any space
just sleeping and surfing
thanks for picking up the trash
why don t you go tell your friend you re not sure you want to live with him because he smoke too much then spend hour begging him to come smoke
hi it kate it wa lovely to see you tonight and ill phone you tomorrow i got to sing and a guy gave me his card xxx
happy new year my dear brother i really do miss you just got your number and decided to send you this text wishing you only happiness abiola
that mean get the door
your opinion about me over jada kusruthi lovable silent spl character not matured stylish simple pls reply
hmmm i thought we said hour slave not you are late how should i punish you
beerage
you have an important customer service announcement from premier call freephone now
dont think so it turn off like randomlly within min of opening
she wa supposed to be but couldn t make it she s still in town though
it doe it on it own most of the time it fix my spelling but sometimes it get a completely diff word go figure
ever thought about living a good life with a perfect partner just txt back name and age to join the mobile community p sm
free top polyphonic tone call national rate get a toppoly tune sent every week just text subpoly to per pole unsub
gud mrng dear hav a nice day
this is hoping you enjoyed your game yesterday sorry i ve not been in touch but pls know that you are fondly bein thot off have a great week abiola
all e best ur driving tmr
y where u at dogbreath it just sounding like jan c that s al
omg i want to scream i weighed myself and i lost more weight woohoo
there generally isn t one it s an uncountable noun u in the dictionary piece of research
it s really getting me down just hanging around
orange customer you may now claim your free camera phone upgrade for your loyalty call now on offer end thmarch t c s apply opt out availa
petey boy whereare you me and all your friendsare in thekingshead come down if you canlove nic
ok i msg u b i leave my house
gimme a few wa lt gt minute ago
last chance claim ur worth of discount voucher today text shop to now savamob offer mobile t c savamob pobox m uz sub
appt is at lt time gt am not my fault u don t listen i told u twice
free for st week no nokia tone ur mobile every week just txt nokia to get txting and tell ur mate www getzed co uk pobox w wq norm p tone
you have won a guaranteed award or even cashto claim ur award call free on stop getstop on php rg jx
k i ll be there before
i dled d it very imp
sure but make sure he know we ain t smokin yet
boooo you always work just quit
i am taking half day leave bec i am not well
ugh i don t wanna get out of bed it s so warm
s s nervous lt gt
so there s a ring that come with the guy costume it s there so they can gift their future yowifes hint hint
congratulation ur awarded either of cd gift voucher free entry our weekly draw txt music to tncs www ldew com win ppmx age
i borrow ur bag ok
u were outbid by simonwatson on the shinco dvd plyr bid again visit sm ac smsrewards end bid notification reply end out
where s my boytoy i miss you what happened
he ha lot of used one babe but the model doesn t help youi have to bring it over and he ll match it up
also are you bringing galileo or dobby
then why you not responding
boo babe u enjoyin yourjob u seemed b gettin on well hunny hope ure ok take care i llspeak u soonlots of loveme xxxx
good afternoon starshine how s my boytoy doe he crave me yet ache to fuck me sip cappuccino i miss you babe teasing kiss
on the road so cant txt
smsservices for yourinclusive text credit pls goto www comuk net login qxj unsubscribe with stop no extra charge help comuk cm ae
p alfie moon s child in need song on ur mob tell ur m s txt tone charity to for nokias or poly charity for polys zed profit charity
have a good evening ttyl
hmm bit and piece lol sigh
hahaha use your brain dear
hey you got any mail
sorry light turned green i meant another friend wanted lt gt worth but he may not be around
thanks for yesterday sir you have been wonderful hope you enjoyed the burial mojibiola
u have a secret admirer reveal who think u r so special call to opt out reply reveal stop per msg recd cust care
hi mate it rv did u hav a nice hol just a message say hello coz haven t sent u in age started driving so stay off road rvx
dear voucher holder to claim this week offer at you pc please go to http www e tlp co uk expressoffer t c apply to stop text txt stop to
thank you so much when we skyped wit kz and sura we didnt get the pleasure of your company hope you are good we ve given you ultimatum oh we are countin down to aburo enjoy this is the message i sent day ago
surely result will offer
good morning my dear have a great amp successful day
do you want anytime any network min text and a new video phone for only five pound per week call or reply for delivery tomorrow
sir i have been late in paying rent for the past few month and had to pay a lt gt charge i felt it would be inconsiderate of me to nag about something you give at great cost to yourself and that s why i didnt speak up i however am in a recession and wont be able to pay the charge this month hence my askin well ahead of month s end can you please help thanks
we tried to contact you re our offer of new video phone anytime any network min half price rental camcorder call or reply for delivery wed

In [145]:
[[i,j,k] for i,j,k in zip(list(map(len,corpus)),corpus, messages['message']) if i<1]

[[0, '', '645'], [0, '', ':) '], [0, '', ':-) :-)']]

In [146]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile update co free on',
 'i m gonna be home soon and i don t want to talk about this stuff anymore tonight k i ve cried enough today',
 'six chance to win cash from to pound txt csh and send to cost p day day tsandcs apply reply hl info',
 'urgent you have won a week free membership in our prize jackpot txt the word claim to no t c www dbuk net lccltd pobox ldnw a rw',
 'i ve been searching for the right word to thank you for this breather i promise i wont take your help for granted and will fulfil my promise you have been wonderful and a blessing at all time',
 'i have a date on sunday with will',
 'xxxmobilemovieclub to use your credit click the wap link in the next txt message or click here http wap xxxmobilemovieclub com n qjkgighjjgcbl',
 'oh k i m watching here',
 'eh u remember how spell his name yes i did he v naughty make until i v wet',
 'fine if that s the way u feel that s the way it gota b',
 'england v macedonia dont miss the goal team news txt ur national team to eg england to try wale scotland txt poboxox w wq',
 'is that seriously how you spell his name',
 'i m going to try for month ha ha only joking',
 'so pay first lar then when is da stock comin',
 'aft i finish my lunch then i go str down lor ard smth lor u finish ur lunch already',
 'ffffffffff alright no way i can meet up with you sooner',
 'just forced myself to eat a slice i m really not hungry tho this suck mark is getting worried he know i m sick when i turn down pizza lol',
 'lol your always so convincing',
 'did you catch the bus are you frying an egg did you make a tea are you eating your mom s left over dinner do you feel my love',
 'i m back amp we re packing the car now i ll let you know if there s room',
 'ahhh work i vaguely remember that what doe it feel like lol',
 'wait that s still not all that clear were you not sure about me being sarcastic or that that s why x doesn t want to live with u',
 'yeah he got in at and wa v apologetic n had fallen out and she wa actin like spoilt child and he got caught up in that till but we won t go there not doing too badly cheer you',
 'k tell me anything about you',
 'for fear of fainting with the of all that housework you just did quick have a cuppa',
 'thanks for your subscription to ringtone uk your mobile will be charged month please confirm by replying yes or no if you reply no you will not be charged',
 'yup ok i go home look at the timing then i msg again xuhui going to learn on nd may too but her lesson is at am',
 'oops i ll let you know when my roommate s done',
 'i see the letter b on my car',
 'anything lor u decide',
 'hello how s you and how did saturday go i wa just texting to see if you d decided to do anything tomo not that i m trying to invite myself or anything',
 'pls go ahead with watt i just wanted to be sure do have a great weekend abiola',
 'did i forget to tell you i want you i need you i crave you but most of all i love you my sweet arabian steed mmmmmm yummy',
 'rodger burn msg we tried to call you re your reply to our sm for a free nokia mobile free camcorder please call now for delivery tomorrow',
 'who are you seeing',
 'great i hope you like your man well endowed i am lt gt inch',
 'no call message missed call',
 'didn t you get hep b immunisation in nigeria',
 'fair enough anything going on',
 'yeah hopefully if tyler can t do it i could maybe ask around a bit',
 'u don t know how stubborn i am i didn t even want to go to the hospital i kept telling mark i m not a weak sucker hospital are for weak sucker',
 'what you thinked about me first time you saw me in class',
 'a gram usually run like lt gt a half eighth is smarter though and get you almost a whole second gram for lt gt',
 'k fyi x ha a ride early tomorrow morning but he s crashing at our place tonight',
 'wow i never realized that you were so embarassed by your accomodations i thought you liked it since i wa doing the best i could and you always seemed so happy about the cave i m sorry i didn t and don t have more to give i m sorry i offered i m sorry your room wa so embarassing',
 'sm ac sptv the new jersey devil and the detroit red wing play ice hockey correct or incorrect end reply end sptv',
 'do you know what mallika sherawat did yesterday find out now lt url gt',
 'congrats year special cinema pas for is yours call now c suprman v matrix starwars etc all free bx ip we pm dont miss out',
 'sorry i ll call later in meeting',
 'tell where you reached',
 'yes gauti and sehwag out of odi series',
 'your gonna have to pick up a burger for yourself on your way home i can t even move pain is killing me',
 'ha ha ha good joke girl are situation seeker',
 'it a part of checking iq',
 'sorry my roommate took forever it ok if i come by now',
 'ok lar i double check wif da hair dresser already he said wun cut v short he said will cut until i look nice',
 'a a valued customer i am pleased to advise you that following recent review of your mob no you are awarded with a bonus prize call',
 'today is song dedicated day which song will u dedicate for me send this to all ur valuable frnds but first rply me',
 'urgent ur awarded a complimentary trip to eurodisinc trav aco entry or to claim txt dis to morefrmmob shracomorsglsuplt l aj',
 'did you hear about the new divorce barbie it come with all of ken s stuff',
 'i plane to give on this month end',
 'wah lucky man then can save money hee',
 'finished class where are you',
 'hi babe im at home now wanna do something xx',
 'k k where are you how did you performed',
 'u can call me now',
 'i am waiting machan call me once you free',
 'thats cool i am a gentleman and will treat you with dignity and respect',
 'i like you people very much but am very shy pa',
 'doe not operate after lt gt or what',
 'it not the same here still looking for a job how much do ta s earn there',
 'sorry i ll call later',
 'k did you call me just now ah',
 'ok i am on the way to home hi hi',
 'you will be in the place of that man',
 'yup next stop',
 'i call you later don t have network if urgnt sm me',
 'for real when u getting on yo i only need more ticket and one more jacket and i m done i already used all my multis',
 'yes i started to send request to make it but pain came back so i m back in bed double coin at the factory too i gotta cash in all my nitros',
 'i m really not up to it still tonight babe',
 'ela kano il download come wen ur free',
 'yeah do don t stand to close tho you ll catch something',
 'sorry to be a pain is it ok if we meet another night i spent late afternoon in casualty and that mean i haven t done any of y stuff moro and that includes all my time sheet and that sorry',
 'smile in pleasure smile in pain smile when trouble pours like rain smile when sum hurt u smile becoz someone still love to see u smiling',
 'please call our customer service representative on between am pm a you have won a guaranteed cash or prize',
 'havent planning to buy later i check already lido only got show in e afternoon u finish work already',
 'your free ringtone is waiting to be collected simply text the password mix to to verify get usher and britney fml po box mk h ppw',
 'watching telugu movie wat abt u',
 'i see when we finish we have load of loan to pay',
 'hi wk been ok on hols now yes on for a bit of a run forgot that i have hairdresser appointment at four so need to get home n shower beforehand doe that cause prob for u',
 'i see a cup of coffee animation',
 'please don t text me anymore i have nothing else to say',
 'okay name ur price a long a it legal wen can i pick them up y u ave x am xx',
 'i m still looking for a car to buy and have not gone the driving test yet',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'wow you re right i didn t mean to do that i guess once i gave up on boston men and changed my search location to nyc something changed cuz on my signin page it still say boston',
 'umma my life and vava umma love you lot dear',
 'thanks a lot for your wish on my birthday thanks you for making my birthday truly memorable',
 'aight i ll hit you up when i get some cash',
 'how would my ip address test that considering my computer isn t a minecraft server',
 'i know grumpy old people my mom wa like you better not be lying then again i am always the one to play joke',
 'dont worry i guess he s busy',
 'what is the plural of the noun research',
 'going for dinner msg you after',
 'i m ok wif it co i like try new thing but i scared u dun like mah co u said not too loud',
 'gent we are trying to contact you last weekend draw show that you won a prize guaranteed call claim code k valid hr only ppm',
 'wa ur openin sentence very formal anyway i m fine too juz tt i m eatin too much n puttin on weight haha so anythin special happened',
 'a i entered my cabin my pa said happy b day bos i felt special she askd me lunch after lunch she invited me to her apartment we went there',
 'you are a winner u have been specially selected receive or a holiday flight inc speak to a live operator claim p min',
 'goodo yes we must speak friday egg potato ratio for tortilla needed',
 'hmm my uncle just informed me that he s paying the school directly so pls buy food',
 'private your account statement for show unredeemed bonus point to claim call identifier code expires',
 'urgent your mobile no wa awarded bonus caller prize on this is our final try to contact u call from landline box wr c ppm',
 'here is my new address apple pair all that malarky',
 'today voda number ending are selected to receive a award if you have a match please call quoting claim code standard rate app',
 'i am going to sao mu today will be done only at',
 'predict wat time ll finish buying',
 'good stuff will do',
 'just so that you know yetunde hasn t sent money yet i just sent her a text not to bother sending so it over you dont have to involve yourself in anything i shouldn t have imposed anything on you in the first place so for that i apologise',
 'are you there in room',
 'hey girl how r u hope u r well me an del r bak again long time no c give me a call sum time from lucyxx',
 'k k how much doe it cost',
 'i m home',
 'dear will call tmorrow pls accomodate',
 'first answer my question',
 'sunshine quiz wkly q win a top sony dvd player if u know which country the algarve is in txt ansr to sp tyrone',
 'want get laid tonight want real dogging location sent direct ur mob join the uk s largest dogging network bt txting gravel to nt ec a p msg p',
 'i only haf msn it s yijue hotmail com',
 'he is there you call and meet him',
 'no no i will check all room befor activity',
 'you ll not rcv any more msg from the chat svc for free hardcore service text go to if u get nothing u must age verify with yr network try again',
 'got c i lazy to type i forgot in lect i saw a pouch but like not v nice',
 'k text me when you re on the way',
 'sir waiting for your mail',
 'a swt thought nver get tired of doing little thing lovable person coz somtimes those little thing occupy d biggest part in their heart gud ni',
 'i know you are can you pls open the back',
 'yes see ya not on the dot',
 'whats the staff name who is taking class for u',
 'freemsg why haven t you replied to my text i m randy sexy female and live local luv to hear from u netcollex ltd p per msg reply stop to end',
 'ummma will call after check in our life will begin from qatar so pls pray very hard',
 'k i deleted my contact that why',
 'sindu got job in birla soft',
 'the wine is flowing and i m i have nevering',
 'yup i thk cine is better co no need go down plaza mah',
 'ok ur typical reply',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'you are everywhere dirt on the floor the window even on my shirt and sometimes when i open my mouth you are all that come flowing out i dream of my world without you then half my chore are out too a time of joy for me lot of tv show i ll see but i guess like all thing you just must exist like rain hail and mist and when my time here is done you and i become one',
 'aaooooright are you at work',
 'i m leaving my house now',
 'hello my love what are you doing did you get to that interview today are you you happy are you being a good boy do you think of me are you missing me',
 'customer service annoncement you have a new year delivery waiting for you please call now to arrange delivery',
 'you are a winner u have been specially selected receive cash or a holiday flight inc speak to a live operator claim',
 'keep yourself safe for me because i need you and i miss you already and i envy everyone that see s you in real life',
 'new car and house for my parent i have only new job in hand',
 'i m so in love with you i m excited each day i spend with you you make me so happy',
 'pls stop bootydelious f is inviting you to be her friend reply yes or no see her www sm ac u bootydelious stop send stop frnd to',
 'bangbabes ur order is on the way u should receive a service msg download ur content if u do not goto wap bangb tv on ur mobile internet service menu',
 'i place all ur point on e culture module already',
 'urgent we are trying to contact you last weekend draw show that you have won a prize guaranteed call claim code s valid hr only',
 'hi frnd which is best way to avoid missunderstding wit our beloved one s',
 'great escape i fancy the bridge but need her lager see you tomo',
 'yes it completely in out of form clark also utter waste',
 'sir i need axis bank account no and bank address',
 'hmmm thk sure got time to hop ard ya can go free abt muz call u to discus liao',
 'what time you coming down later',
 'bloody hell cant believe you forgot my surname mr ill give u a clue it spanish and begin with m',
 'well i m gonna finish my bath now have a good fine night',
 'let me know when you ve got the money so carlos can make the call',
 'u still going to the mall',
 'turn out my friend are staying for the whole show and won t be back til lt gt so feel free to go ahead and smoke that lt gt worth',
 'text her if she doesnt reply let me know so i can have her log in',
 'hi you just spoke to maneesha v we d like to know if you were satisfied with the experience reply toll free with yes or no',
 'you lifted my hope with the offer of money i am in need especially when the end of the month approach and it hurt my studying anyways have a gr weekend',
 'lol no u can trust me',
 'ok i am a gentleman and will treat you with dignity and respect',
 'he will you guy close',
 'going on nothing great bye',
 'hello handsome are you finding that job not being lazy working towards getting back that net for mummy where s my boytoy now doe he miss me',
 'haha awesome be there in a minute',
 'please call our customer service representative on freephone between am pm a you have won a guaranteed cash or prize',
 'have you got xmas radio time if not i will get it now',
 'i jus reached home i go bathe first but my si using net tell u when she finish k',
 'are you unique enough find out from th august www areyouunique co uk',
 'i m sorry i ve joined the league of people that dont keep in touch you mean a great deal to me you have been a friend at all time even at great personal cost do have a great week',
 'hi finally i completed the course',
 'it will stop on itself i however suggest she stay with someone that will be able to give or for every stool',
 'how are you doing hope you ve settled in for the new school year just wishin you a gr day',
 'gud mrng dear hav a nice day',
 'did u got that person story',
 'is your hamster dead hey so tmr i meet you at pm orchard mrt',
 'hi it kate how is your evening i hope i can see you tomorrow for a bit but i have to bloody babyjontet txt back if u can xxx',
 'found it enc lt gt where you at',
 'i sent you lt gt buck',
 'hello darlin ive finished college now so txt me when u finish if u can love kate xxx',
 'your account ha been refilled successfully by inr lt decimal gt your keralacircle prepaid account balance is r lt decimal gt your transaction id is kr lt gt',
 'goodmorning sleeping ga',
 'u call me alter at ok',
 'say until like dat i dun buy ericsson oso cannot oredi lar',
 'a i entered my cabin my pa said happy b day bos i felt special she askd me lunch after lunch she invited me to her apartment we went there',
 'aight yo dat straight dogg',
 'you please give u connection today itself before lt decimal gt or refund the bill',
 'both i shoot big load so get ready',
 'what s up bruv hope you had a great break do have a rewarding semester',
 'home so we can always chat',
 'k k good study well',
 'yup how noe leh',
 'sound great are you home now',
 'finally the match heading towards draw a your prediction',
 'tired i haven t slept well the past few night',
 'easy ah sen got selected mean it good',
 'i have to take exam with march',
 'yeah you should i think you can use your gt atm now to register not sure but if there s anyway i can help let me know but when you do be sure you are ready',
 'ok no prob take ur time',
 'there is o called ubandu which will run without installing in hard disk you can use that o to copy the important file in system and give it to repair shop',
 'sorry i ll call later',
 'u say leh of course nothing happen lar not say v romantic jus a bit only lor i thk e nite scenery not so nice leh',
 'new mobile from must go txt nokia to no collect yours today from only www tc biz optout gbp mtmsg',
 'would really appreciate if you call me just need someone to talk to',
 'will u meet ur dream partner soon is ur career off a flyng start find out free txt horo followed by ur star sign e g horo aries',
 'hey company elama po mudyadhu',
 'life is more strict than teacher bcoz teacher teach lesson amp then conduct exam but life first conduct exam amp then teach lesson happy morning',
 'dear good morning now only i am up',
 'get down in gandhipuram and walk to cross cut road right side lt gt street road and turn at first right',
 'dear we are going to our rubber place',
 'sorry battery died yeah i m here',
 'yes here tv is always available in work place',
 'text meet someone sexy today u can find a date or even flirt it up to u join just p reply with name age eg sam msg recd thirtyeight penny',
 'i have printed it oh so lt gt come upstairs',
 'or ill be a little closer like at the bus stop on the same street',
 'where are you when wil you reach here',
 'new theory argument win d situation but loses the person so dont argue with ur friend just kick them amp say i m always correct',
 'u have a secret admirer who is looking make contact with u find out who they r reveal who think ur so special call on',
 'tomarrow final hearing on my laptop case so i cant',
 'pleassssssseeeeee tel me v avent done sportsx',
 'okay no no just shining on that wa meant to be signing but that sound better',

In [147]:
# Alternate way of doing
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [148]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [149]:
words=[]
for sent in corpus:
  sent_token = sent_tokenize(sent)
  for sent in sent_token:
    words.append(simple_preprocess(sent))

In [150]:
words

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'speak',
  'with',
  'me',
  'they',
  'treat',
  'me',
  'like',
  'aid',
  'patent'],
 ['per',
  'your',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'ha',
  'been',
  'set',
  'your',
  'callertune',
  'for',
  'all',
  'caller',
  'press',
  'to',
  'copy',
  'your',
  'friend',
  'callertune'],
 ['winner',
  'valued',
  'network',
  'customer',
  'you',
  'have',
  'been',
  'selected',
  'to',
  'receivea',
  'prize',
  'reward',
  'to',
  'claim',
  'call',
  'claim',
  'code',
  'kl',
  'valid',
  'hour',
  'only'],
 ['had',
  'your',
  'mobile',
  'month',
  'or',
  'more',
  'entitled',
  'to',
  'update',
  'to',
  'the',
  'latest',
  'colour',
  'mobile',
  'with',
  'camera',
  'for',
  'free',
  'call',
  'the',
  'mobile',
  'update',
  'co',
  'free',
  'on'],
 ['gonna',
  'be',
  'home',
  'soon',
  'and',
  'don',
  'want',
  'to',
  'talk',
  'about',
  'this',
  'stuff',
  'anymore',
  'tonight',
  've',
  'cried',
  'enough',
  'today'],
 ['six',
  'chance',
  'to',
  'win',
  'cash',
  'from',
  'to',
  'pound',
  'txt',
  'csh',
  'and',
  'send',
  'to',
  'cost',
  'day',
  'day',
  'tsandcs',
  'apply',
  'reply',
  'hl',
  'info'],
 ['urgent',
  'you',
  'have',
  'won',
  'week',
  'free',
  'membership',
  'in',
  'our',
  'prize',
  'jackpot',
  'txt',
  'the',
  'word',
  'claim',
  'to',
  'no',
  'www',
  'dbuk',
  'net',
  'lccltd',
  'pobox',
  'ldnw',
  'rw'],
 ['ve',
  'been',
  'searching',
  'for',
  'the',
  'right',
  'word',
  'to',
  'thank',
  'you',
  'for',
  'this',
  'breather',
  'promise',
  'wont',
  'take',
  'your',
  'help',
  'for',
  'granted',
  'and',
  'will',
  'fulfil',
  'my',
  'promise',
  'you',
  'have',
  'been',
  'wonderful',
  'and',
  'blessing',
  'at',
  'all',
  'time'],
 ['have', 'date', 'on', 'sunday', 'with', 'will'],
 ['to',
  'use',
  'your',
  'credit',
  'click',
  'the',
  'wap',
  'link',
  'in',
  'the',
  'next',
  'txt',
  'message',
  'or',
  'click',
  'here',
  'http',
  'wap',
  'com',
  'qjkgighjjgcbl'],
 ['oh', 'watching', 'here'],
 ['eh',
  'remember',
  'how',
  'spell',
  'his',
  'name',
  'yes',
  'did',
  'he',
  'naughty',
  'make',
  'until',
  'wet'],
 ['fine',
  'if',
  'that',
  'the',
  'way',
  'feel',
  'that',
  'the',
  'way',
  'it',
  'gota'],
 ['england',
  'macedonia',
  'dont',
  'miss',
  'the',
  'goal',
  'team',
  'news',
  'txt',
  'ur',
  'national',
  'team',
  'to',
  'eg',
  'england',
  'to',
  'try',
  'wale',
  'scotland',
  'txt',
  'poboxox',
  'wq'],
 ['is', 'that', 'seriously', 'how', 'you', 'spell', 'his', 'name'],
 ['going', 'to', 'try', 'for', 'month', 'ha', 'ha', 'only', 'joking'],
 ['so', 'pay', 'first', 'lar', 'then', 'when', 'is', 'da', 'stock', 'comin'],
 ['aft',
  'finish',
  'my',
  'lunch',
  'then',
  'go',
  'str',
  'down',
  'lor',
  'ard',
  'smth',
  'lor',
  'finish',
  'ur',
  'lunch',
  'already'],
 ['ffffffffff',
  'alright',
  'no',
  'way',
  'can',
  'meet',
  'up',
  'with',
  'you',
  'sooner'],
 ['just',
  'forced',
  'myself',
  'to',
  'eat',
  'slice',
  'really',
  'not',
  'hungry',
  'tho',
  'this',
  'suck',
  'mark',
  'is',
  'getting',
  'worried',
  'he',
  'know',
  'sick',
  'when',
  'turn',
  'down',
  'pizza',
  'lol'],
 ['lol', 'your', 'always', 'so', 'convincing'],
 ['did',
  'you',
  'catch',
  'the',
  'bus',
  'are',
  'you',
  'frying',
  'an',
  'egg',
  'did',
  'you',
  'make',
  'tea',
  'are',
  'you',
  'eating',
  'your',
  'mom',
  'left',
  'over',
  'dinner',
  'do',
  'you',
  'feel',
  'my',
  'love'],
 ['back',
  'amp',
  'we',
  're',
  'packing',
  'the',
  'car',
  'now',
  'll',
  'let',
  'you',
  'know',
  'if',
  'there',
  'room'],
 ['ahhh',
  'work',
  'vaguely',
  'remember',
  'that',
  'what',
  'doe',
  'it',
  'feel',
  'like',
  'lol'],
 ['wait',
  'that',
  'still',
  'not',
  'all',
  'that',
  'clear',
  'were',
  'you',
  'not',
  'sure',
  'about',
  'me',
  'being',
  'sarcastic',
  'or',
  'that',
  'that',
  'why',
  'doesn',
  'want',
  'to',
  'live',
  'with'],
 ['yeah',
  'he',
  'got',
  'in',
  'at',
  'and',
  'wa',
  'apologetic',
  'had',
  'fallen',
  'out',
  'and',
  'she',
  'wa',
  'actin',
  'like',
  'spoilt',
  'child',
  'and',
  'he',
  'got',
  'caught',
  'up',
  'in',
  'that',
  'till',
  'but',
  'we',
  'won',
  'go',
  'there',
  'not',
  'doing',
  'too',
  'badly',
  'cheer',
  'you'],
 ['tell', 'me', 'anything', 'about', 'you'],
 ['for',
  'fear',
  'of',
  'fainting',
  'with',
  'the',
  'of',
  'all',
  'that',
  'housework',
  'you',
  'just',
  'did',
  'quick',
  'have',
  'cuppa'],
 ['thanks',
  'for',
  'your',
  'subscription',
  'to',
  'ringtone',
  'uk',
  'your',
  'mobile',
  'will',
  'be',
  'charged',
  'month',
  'please',
  'confirm',
  'by',
  'replying',
  'yes',
  'or',
  'no',
  'if',
  'you',
  'reply',
  'no',
  'you',
  'will',
  'not',
  'be',
  'charged'],
 ['yup',
  'ok',
  'go',
  'home',
  'look',
  'at',
  'the',
  'timing',
  'then',
  'msg',
  'again',
  'xuhui',
  'going',
  'to',
  'learn',
  'on',
  'nd',
  'may',
  'too',
  'but',
  'her',
  'lesson',
  'is',
  'at',
  'am'],
 ['oops', 'll', 'let', 'you', 'know', 'when', 'my', 'roommate', 'done'],
 ['see', 'the', 'letter', 'on', 'my', 'car'],
 ['anything', 'lor', 'decide'],
 ['hello',
  'how',
  'you',
  'and',
  'how',
  'did',
  'saturday',
  'go',
  'wa',
  'just',
  'texting',
  'to',
  'see',
  'if',
  'you',
  'decided',
  'to',
  'do',
  'anything',
  'tomo',
  'not',
  'that',
  'trying',
  'to',
  'invite',
  'myself',
  'or',
  'anything'],
 ['pls',
  'go',
  'ahead',
  'with',
  'watt',
  'just',
  'wanted',
  'to',
  'be',
  'sure',
  'do',
  'have',
  'great',
  'weekend',
  'abiola'],
 ['did',
  'forget',
  'to',
  'tell',
  'you',
  'want',
  'you',
  'need',
  'you',
  'crave',
  'you',
  'but',
  'most',
  'of',
  'all',
  'love',
  'you',
  'my',
  'sweet',
  'arabian',
  'steed',
  'mmmmmm',
  'yummy'],
 ['rodger',
  'burn',
  'msg',
  'we',
  'tried',
  'to',
  'call',
  'you',
  're',
  'your',
  'reply',
  'to',
  'our',
  'sm',
  'for',
  'free',
  'nokia',
  'mobile',
  'free',
  'camcorder',
  'please',
  'call',
  'now',
  'for',
  'delivery',
  'tomorrow'],
 ['who', 'are', 'you', 'seeing'],
 ['great',
  'hope',
  'you',
  'like',
  'your',
  'man',
  'well',
  'endowed',
  'am',
  'lt',
  'gt',
  'inch'],
 ['no', 'call', 'message', 'missed', 'call'],
 ['didn', 'you', 'get', 'hep', 'immunisation', 'in', 'nigeria'],
 ['fair', 'enough', 'anything', 'going', 'on'],
 ['yeah',
  'hopefully',
  'if',
  'tyler',
  'can',
  'do',
  'it',
  'could',
  'maybe',
  'ask',
  'around',
  'bit'],
 ['don',
  'know',
  'how',
  'stubborn',
  'am',
  'didn',
  'even',
  'want',
  'to',
  'go',
  'to',
  'the',
  'hospital',
  'kept',
  'telling',
  'mark',
  'not',
  'weak',
  'sucker',
  'hospital',
  'are',
  'for',
  'weak',
  'sucker'],
 ['what',
  'you',
  'thinked',
  'about',
  'me',
  'first',
  'time',
  'you',
  'saw',
  'me',
  'in',
  'class'],
 ['gram',
  'usually',
  'run',
  'like',
  'lt',
  'gt',
  'half',
  'eighth',
  'is',
  'smarter',
  'though',
  'and',
  'get',
  'you',
  'almost',
  'whole',
  'second',
  'gram',
  'for',
  'lt',
  'gt'],
 ['fyi',
  'ha',
  'ride',
  'early',
  'tomorrow',
  'morning',
  'but',
  'he',
  'crashing',
  'at',
  'our',
  'place',
  'tonight'],
 ['wow',
  'never',
  'realized',
  'that',
  'you',
  'were',
  'so',
  'embarassed',
  'by',
  'your',
  'accomodations',
  'thought',
  'you',
  'liked',
  'it',
  'since',
  'wa',
  'doing',
  'the',
  'best',
  'could',
  'and',
  'you',
  'always',
  'seemed',
  'so',
  'happy',
  'about',
  'the',
  'cave',
  'sorry',
  'didn',
  'and',
  'don',
  'have',
  'more',
  'to',
  'give',
  'sorry',
  'offered',
  'sorry',
  'your',
  'room',
  'wa',
  'so',
  'embarassing'],
 ['sm',
  'ac',
  'sptv',
  'the',
  'new',
  'jersey',
  'devil',
  'and',
  'the',
  'detroit',
  'red',
  'wing',
  'play',
  'ice',
  'hockey',
  'correct',
  'or',
  'incorrect',
  'end',
  'reply',
  'end',
  'sptv'],
 ['do',
  'you',
  'know',
  'what',
  'mallika',
  'sherawat',
  'did',
  'yesterday',
  'find',
  'out',
  'now',
  'lt',
  'url',
  'gt'],
 ['congrats',
  'year',
  'special',
  'cinema',
  'pas',
  'for',
  'is',
  'yours',
  'call',
  'now',
  'suprman',
  'matrix',
  'starwars',
  'etc',
  'all',
  'free',
  'bx',
  'ip',
  'we',
  'pm',
  'dont',
  'miss',
  'out'],
 ['sorry', 'll', 'call', 'later', 'in', 'meeting'],
 ['tell', 'where', 'you', 'reached'],
 ['yes', 'gauti', 'and', 'sehwag', 'out', 'of', 'odi', 'series'],
 ['your',
  'gonna',
  'have',
  'to',
  'pick',
  'up',
  'burger',
  'for',
  'yourself',
  'on',
  'your',
  'way',
  'home',
  'can',
  'even',
  'move',
  'pain',
  'is',
  'killing',
  'me'],
 ['ha', 'ha', 'ha', 'good', 'joke', 'girl', 'are', 'situation', 'seeker'],
 ['it', 'part', 'of', 'checking', 'iq'],
 ['sorry',
  'my',
  'roommate',
  'took',
  'forever',
  'it',
  'ok',
  'if',
  'come',
  'by',
  'now'],
 ['ok',
  'lar',
  'double',
  'check',
  'wif',
  'da',
  'hair',
  'dresser',
  'already',
  'he',
  'said',
  'wun',
  'cut',
  'short',
  'he',
  'said',
  'will',
  'cut',
  'until',
  'look',
  'nice'],
 ['valued',
  'customer',
  'am',
  'pleased',
  'to',
  'advise',
  'you',
  'that',
  'following',
  'recent',
  'review',
  'of',
  'your',
  'mob',
  'no',
  'you',
  'are',
  'awarded',
  'with',
  'bonus',
  'prize',
  'call'],
 ['today',
  'is',
  'song',
  'dedicated',
  'day',
  'which',
  'song',
  'will',
  'dedicate',
  'for',
  'me',
  'send',
  'this',
  'to',
  'all',
  'ur',
  'valuable',
  'frnds',
  'but',
  'first',
  'rply',
  'me'],
 ['urgent',
  'ur',
  'awarded',
  'complimentary',
  'trip',
  'to',
  'eurodisinc',
  'trav',
  'aco',
  'entry',
  'or',
  'to',
  'claim',
  'txt',
  'dis',
  'to',
  'morefrmmob',
  'aj'],
 ['did',
  'you',
  'hear',
  'about',
  'the',
  'new',
  'divorce',
  'barbie',
  'it',
  'come',
  'with',
  'all',
  'of',
  'ken',
  'stuff'],
 ['plane', 'to', 'give', 'on', 'this', 'month', 'end'],
 ['wah', 'lucky', 'man', 'then', 'can', 'save', 'money', 'hee'],
 ['finished', 'class', 'where', 'are', 'you'],
 ['hi', 'babe', 'im', 'at', 'home', 'now', 'wanna', 'do', 'something', 'xx'],
 ['where', 'are', 'you', 'how', 'did', 'you', 'performed'],
 ['can', 'call', 'me', 'now'],
 ['am', 'waiting', 'machan', 'call', 'me', 'once', 'you', 'free'],
 ['thats',
  'cool',
  'am',
  'gentleman',
  'and',
  'will',
  'treat',
  'you',
  'with',
  'dignity',
  'and',
  'respect'],
 ['like', 'you', 'people', 'very', 'much', 'but', 'am', 'very', 'shy', 'pa'],
 ['doe', 'not', 'operate', 'after', 'lt', 'gt', 'or', 'what'],
 ['it',
  'not',
  'the',
  'same',
  'here',
  'still',
  'looking',
  'for',
  'job',
  'how',
  'much',
  'do',
  'ta',
  'earn',
  'there'],
 ['sorry', 'll', 'call', 'later'],
 ['did', 'you', 'call', 'me', 'just', 'now', 'ah'],
 ['ok', 'am', 'on', 'the', 'way', 'to', 'home', 'hi', 'hi'],
 ['you', 'will', 'be', 'in', 'the', 'place', 'of', 'that', 'man'],
 ['yup', 'next', 'stop'],
 ['call', 'you', 'later', 'don', 'have', 'network', 'if', 'urgnt', 'sm', 'me'],
 ['for',
  'real',
  'when',
  'getting',
  'on',
  'yo',
  'only',
  'need',
  'more',
  'ticket',
  'and',
  'one',
  'more',
  'jacket',
  'and',
  'done',
  'already',
  'used',
  'all',
  'my',
  'multis'],
 ['yes',
  'started',
  'to',
  'send',
  'request',
  'to',
  'make',
  'it',
  'but',
  'pain',
  'came',
  'back',
  'so',
  'back',
  'in',
  'bed',
  'double',
  'coin',
  'at',
  'the',
  'factory',
  'too',
  'gotta',
  'cash',
  'in',
  'all',
  'my',
  'nitros'],
 ['really', 'not', 'up', 'to', 'it', 'still', 'tonight', 'babe'],
 ['ela', 'kano', 'il', 'download', 'come', 'wen', 'ur', 'free'],
 ['yeah',
  'do',
  'don',
  'stand',
  'to',
  'close',
  'tho',
  'you',
  'll',
  'catch',
  'something'],
 ['sorry',
  'to',
  'be',
  'pain',
  'is',
  'it',
  'ok',
  'if',
  'we',
  'meet',
  'another',
  'night',
  'spent',
  'late',
  'afternoon',
  'in',
  'casualty',
  'and',
  'that',
  'mean',
  'haven',
  'done',
  'any',
  'of',
  'stuff',
  'moro',
  'and',
  'that',
  'includes',
  'all',
  'my',
  'time',
  'sheet',
  'and',
  'that',
  'sorry'],
 ['smile',
  'in',
  'pleasure',
  'smile',
  'in',
  'pain',
  'smile',
  'when',
  'trouble',
  'pours',
  'like',
  'rain',
  'smile',
  'when',
  'sum',
  'hurt',
  'smile',
  'becoz',
  'someone',
  'still',
  'love',
  'to',
  'see',
  'smiling'],
 ['please',
  'call',
  'our',
  'customer',
  'service',
  'representative',
  'on',
  'between',
  'am',
  'pm',
  'you',
  'have',
  'won',
  'guaranteed',
  'cash',
  'or',
  'prize'],
 ['havent',
  'planning',
  'to',
  'buy',
  'later',
  'check',
  'already',
  'lido',
  'only',
  'got',
  'show',
  'in',
  'afternoon',
  'finish',
  'work',
  'already'],
 ['your',
  'free',
  'ringtone',
  'is',
  'waiting',
  'to',
  'be',
  'collected',
  'simply',
  'text',
  'the',
  'password',
  'mix',
  'to',
  'to',
  'verify',
  'get',
  'usher',
  'and',
  'britney',
  'fml',
  'po',
  'box',
  'mk',
  'ppw'],
 ['watching', 'telugu', 'movie', 'wat', 'abt'],
 ['see',
  'when',
  'we',
  'finish',
  'we',
  'have',
  'load',
  'of',
  'loan',
  'to',
  'pay'],
 ['hi',
  'wk',
  'been',
  'ok',
  'on',
  'hols',
  'now',
  'yes',
  'on',
  'for',
  'bit',
  'of',
  'run',
  'forgot',
  'that',
  'have',
  'hairdresser',
  'appointment',
  'at',
  'four',
  'so',
  'need',
  'to',
  'get',
  'home',
  'shower',
  'beforehand',
  'doe',
  'that',
  'cause',
  'prob',
  'for'],
 ['see', 'cup', 'of', 'coffee', 'animation'],
 ['please',
  'don',
  'text',
  'me',
  'anymore',
  'have',
  'nothing',
  'else',
  'to',
  'say'],
 ['okay',
  'name',
  'ur',
  'price',
  'long',
  'it',
  'legal',
  'wen',
  'can',
  'pick',
  'them',
  'up',
  'ave',
  'am',
  'xx'],
 ['still',
  'looking',
  'for',
  'car',
  'to',
  'buy',
  'and',
  'have',
  'not',
  'gone',
  'the',
  'driving',
  'test',
  'yet'],
 ['per',
  'your',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'ha',
  'been',
  'set',
  'your',
  'callertune',
  'for',
  'all',
  'caller',
  'press',
  'to',
  'copy',
  'your',
  'friend',
  'callertune'],
 ['wow',
  'you',
  're',
  'right',
  'didn',
  'mean',
  'to',
  'do',
  'that',
  'guess',
  'once',
  'gave',
  'up',
  'on',
  'boston',
  'men',
  'and',
  'changed',
  'my',
  'search',
  'location',
  'to',
  'nyc',
  'something',
  'changed',
  'cuz',
  'on',
  'my',
  'signin',
  'page',
  'it',
  'still',
  'say',
  'boston'],
 ['umma', 'my', 'life', 'and', 'vava', 'umma', 'love', 'you', 'lot', 'dear'],
 ['thanks',
  'lot',
  'for',
  'your',
  'wish',
  'on',
  'my',
  'birthday',
  'thanks',
  'you',
  'for',
  'making',
  'my',
  'birthday',
  'truly',
  'memorable'],
 ['aight', 'll', 'hit', 'you', 'up', 'when', 'get', 'some', 'cash'],
 ['how',
  'would',
  'my',
  'ip',
  'address',
  'test',
  'that',
  'considering',
  'my',
  'computer',
  'isn',
  'minecraft',
  'server'],
 ['know',
  'grumpy',
  'old',
  'people',
  'my',
  'mom',
  'wa',
  'like',
  'you',
  'better',
  'not',
  'be',
  'lying',
  'then',
  'again',
  'am',
  'always',
  'the',
  'one',
  'to',
  'play',
  'joke'],
 ['dont', 'worry', 'guess', 'he', 'busy'],
 ['what', 'is', 'the', 'plural', 'of', 'the', 'noun', 'research'],
 ['going', 'for', 'dinner', 'msg', 'you', 'after'],
 ['ok',
  'wif',
  'it',
  'co',
  'like',
  'try',
  'new',
  'thing',
  'but',
  'scared',
  'dun',
  'like',
  'mah',
  'co',
  'said',
  'not',
  'too',
  'loud'],
 ['gent',
  'we',
  'are',
  'trying',
  'to',
  'contact',
  'you',
  'last',
  'weekend',
  'draw',
  'show',
  'that',
  'you',
  'won',
  'prize',
  'guaranteed',
  'call',
  'claim',
  'code',
  'valid',
  'hr',
  'only',
  'ppm'],
 ['wa',
  'ur',
  'openin',
  'sentence',
  'very',
  'formal',
  'anyway',
  'fine',
  'too',
  'juz',
  'tt',
  'eatin',
  'too',
  'much',
  'puttin',
  'on',
  'weight',
  'haha',
  'so',
  'anythin',
  'special',
  'happened'],
 ['entered',
  'my',
  'cabin',
  'my',
  'pa',
  'said',
  'happy',
  'day',
  'bos',
  'felt',
  'special',
  'she',
  'askd',
  'me',
  'lunch',
  'after',
  'lunch',
  'she',
  'invited',
  'me',
  'to',
  'her',
  'apartment',
  'we',
  'went',
  'there'],
 ['you',
  'are',
  'winner',
  'have',
  'been',
  'specially',
  'selected',
  'receive',
  'or',
  'holiday',
  'flight',
  'inc',
  'speak',
  'to',
  'live',
  'operator',
  'claim',
  'min'],
 ['goodo',
  'yes',
  'we',
  'must',
  'speak',
  'friday',
  'egg',
  'potato',
  'ratio',
  'for',
  'tortilla',
  'needed'],
 ['hmm',
  'my',
  'uncle',
  'just',
  'informed',
  'me',
  'that',
  'he',
  'paying',
  'the',
  'school',
  'directly',
  'so',
  'pls',
  'buy',
  'food'],
 ['private',
  'your',
  'account',
  'statement',
  'for',
  'show',
  'unredeemed',
  'bonus',
  'point',
  'to',
  'claim',
  'call',
  'identifier',
  'code',
  'expires'],
 ['urgent',
  'your',
  'mobile',
  'no',
  'wa',
  'awarded',
  'bonus',
  'caller',
  'prize',
  'on',
  'this',
  'is',
  'our',
  'final',
  'try',
  'to',
  'contact',
  'call',
  'from',
  'landline',
  'box',
  'wr',
  'ppm'],
 ['here',
  'is',
  'my',
  'new',
  'address',
  'apple',
  'pair',
  'all',
  'that',
  'malarky'],
 ['today',
  'voda',
  'number',
  'ending',
  'are',
  'selected',
  'to',
  'receive',
  'award',
  'if',
  'you',
  'have',
  'match',
  'please',
  'call',
  'quoting',
  'claim',
  'code',
  'standard',
  'rate',
  'app'],
 ['am',
  'going',
  'to',
  'sao',
  'mu',
  'today',
  'will',
  'be',
  'done',
  'only',
  'at'],
 ['predict', 'wat', 'time', 'll', 'finish', 'buying'],
 ['good', 'stuff', 'will', 'do'],
 ['just',
  'so',
  'that',
  'you',
  'know',
  'yetunde',
  'hasn',
  'sent',
  'money',
  'yet',
  'just',
  'sent',
  'her',
  'text',
  'not',
  'to',
  'bother',
  'sending',
  'so',
  'it',
  'over',
  'you',
  'dont',
  'have',
  'to',
  'involve',
  'yourself',
  'in',
  'anything',
  'shouldn',
  'have',
  'imposed',
  'anything',
  'on',
  'you',
  'in',
  'the',
  'first',
  'place',
  'so',
  'for',
  'that',
  'apologise'],
 ['are', 'you', 'there', 'in', 'room'],
 ['hey',
  'girl',
  'how',
  'hope',
  'well',
  'me',
  'an',
  'del',
  'bak',
  'again',
  'long',
  'time',
  'no',
  'give',
  'me',
  'call',
  'sum',
  'time',
  'from',
  'lucyxx'],
 ['how', 'much', 'doe', 'it', 'cost'],
 ['home'],
 ['dear', 'will', 'call', 'tmorrow', 'pls', 'accomodate'],
 ['first', 'answer', 'my', 'question'],
 ['sunshine',
  'quiz',
  'wkly',
  'win',
  'top',
  'sony',
  'dvd',
  'player',
  'if',
  'know',
  'which',
  'country',
  'the',
  'algarve',
  'is',
  'in',
  'txt',
  'ansr',
  'to',
  'sp',
  'tyrone'],
 ['want',
  'get',
  'laid',
  'tonight',
  'want',
  'real',
  'dogging',
  'location',
  'sent',
  'direct',
  'ur',

In [151]:
import gensim

In [152]:
# Training Word2Vec from scratch
model=gensim.models.Word2Vec(words)

In [153]:
#model.wv.index_to_key # Shows vocabulary

In [154]:
model.corpus_count

5569

In [155]:
model.epochs

5

In [156]:
model.wv.similar_by_word('call')

[('claim', 0.9976193904876709),
 ('text', 0.9965701699256897),
 ('prize', 0.9962393641471863),
 ('mobile', 0.9960521459579468),
 ('txt', 0.9958261847496033),
 ('reply', 0.995278537273407),
 ('stop', 0.995154082775116),
 ('guaranteed', 0.9951165914535522),
 ('or', 0.9947627782821655),
 ('free', 0.9947421550750732)]

In [157]:
model.wv['call']

array([-0.14775842,  0.39366704,  0.25620392,  0.15819733,  0.06406327,
       -0.77445763,  0.33363098,  0.6360363 , -0.418641  , -0.331761  ,
       -0.18296011, -0.5771401 , -0.21597974,  0.02047019,  0.2619678 ,
       -0.21698205,  0.05940175, -0.5259019 , -0.04383253, -0.7688238 ,
        0.13927415,  0.195434  ,  0.15907088, -0.38754958, -0.00365908,
       -0.01956029, -0.35858303, -0.1947871 , -0.35530043,  0.05573542,
        0.34573832, -0.05948807,  0.20432799, -0.19361307, -0.15766259,
        0.5419979 ,  0.22298087, -0.27512532, -0.35335475, -0.74745643,
       -0.00634437, -0.41776234, -0.30107477,  0.00522718,  0.18440819,
        0.06640933, -0.16340356, -0.07195646,  0.32240242,  0.13265741,
        0.2786338 , -0.4591831 ,  0.03628734,  0.16178548, -0.32796347,
        0.15134984,  0.2348989 ,  0.01925284, -0.6758317 ,  0.2275516 ,
        0.01324601,  0.05951152, -0.05098241, -0.17505161, -0.44927505,
        0.40617925,  0.03672523,  0.3533215 , -0.5591313 ,  0.60742176,
       -0.30668318,  0.47005582,  0.5774125 , -0.12257668,  0.54480934,
        0.0716702 ,  0.05856402, -0.18729302, -0.21867007,  0.08919092,
       -0.3120578 , -0.1485555 , -0.37323663,  0.5114251 , -0.10593048,
       -0.05812413, -0.06541798,  0.20238501,  0.55670136,  0.1575535 ,
        0.4628504 ,  0.22004443, -0.04356889, -0.06914691,  0.65149254,
        0.17414217, -0.07790772, -0.42677715,  0.32172224,  0.0518763 ],
      dtype=float32)

In [158]:
model.wv['call'].shape

(100,)

In [159]:
# each word is represented in a sentence is represented as vector with 100 dimensions
# Avg word2vec is to take average of those words and represent the whole sentence in a vector with 100 dimensions
import numpy
def avg_word2vec(doc):
  return numpy.mean([model.wv[word] for word in doc if word in model.wv.index_to_key], axis=0)

In [160]:
#X=[]
#for i in range(len(words)):
#  X.append(avg_word2vec(words[i]))

In [161]:
X = numpy.empty((len(words), len(avg_word2vec(words[0]))))
for i in range(len(words)):
    X[i] = avg_word2vec(words[i])

/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

In [162]:
len(X)

5569

In [163]:
X[0] #first sentence

array([-1.31063059e-01,  2.22093210e-01,  1.33460492e-01,  8.46046209e-02,
        7.41539448e-02, -4.90187049e-01,  2.17659727e-01,  4.70295489e-01,
       -2.78467268e-01, -1.72695771e-01, -1.42873600e-01, -3.83197635e-01,
       -8.32396969e-02,  3.69384289e-02,  2.03034610e-01, -1.30700931e-01,
        7.40657374e-02, -3.19420606e-01, -4.65278141e-03, -5.55394888e-01,
        1.69022098e-01,  9.40073356e-02,  1.25058562e-01, -2.28934541e-01,
       -2.75605675e-02,  2.00310260e-05, -1.99647635e-01, -2.20826760e-01,
       -2.59268314e-01,  2.92104296e-02,  2.79145032e-01, -3.50250043e-02,
        1.53536841e-01, -1.61922857e-01, -1.31570190e-01,  3.70556802e-01,
        3.85879874e-02, -1.53245464e-01, -1.72423139e-01, -4.74614531e-01,
        5.06143644e-02, -2.13621452e-01, -1.69721931e-01,  1.13049140e-02,
        1.82618827e-01,  2.52432656e-02, -1.61479726e-01, -6.13935478e-02,
        2.20038176e-01,  8.24712142e-02,  1.69867247e-01, -2.02590957e-01,
        1.33852549e-02,  3.22709717e-02, -1.24030121e-01,  1.12943068e-01,
        1.79237410e-01,  5.30506372e-02, -4.15620655e-01,  1.23880036e-01,
        1.19392714e-02,  9.14924294e-02, -7.60661885e-02, -1.07128136e-01,
       -2.67804116e-01,  2.50616431e-01,  4.74477261e-02,  2.53557146e-01,
       -3.05707604e-01,  3.64029676e-01, -2.03098521e-01,  1.87882930e-01,
        4.19869572e-01, -6.83514550e-02,  3.82404506e-01,  5.11844978e-02,
        8.23311880e-02, -1.07406072e-01, -1.69697419e-01,  1.00188978e-01,
       -2.24404499e-01, -7.44785070e-02, -2.42287964e-01,  4.20883179e-01,
       -1.46421149e-01, -6.54101223e-02,  4.85853292e-02,  2.16542482e-01,
        3.87773991e-01,  2.21827198e-02,  3.41266364e-01,  1.67039454e-01,
        1.26627339e-02,  4.26631197e-02,  4.58498478e-01,  1.96532592e-01,
        8.82653967e-02, -2.41204947e-01,  2.08174333e-01, -8.65648093e-04])

In [164]:
X_new=numpy.array(X)

In [165]:
X_new.shape

(5569, 100)

In [166]:
X[0].shape

(100,)

In [167]:
## Dependent feature
y= messages[list(map(lambda x: len(x)>0, corpus))]
y=pd.get_dummies(y['label'])
y=y.iloc[:,0].values.astype(int)

In [168]:
y.shape

(5569,)

In [169]:
# Converting to dataFrame
df = pd.DataFrame()
for i in range(0,len(X)):
    df = pd.concat([df, pd.DataFrame(X[i].reshape(1, -1))], ignore_index=True)

In [170]:
df

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.131063,0.222093,0.133460,0.084605,0.074154,-0.490187,0.217660,0.470295,-0.278467,-0.172696,...,0.341266,0.167039,0.012663,0.042663,0.458498,0.196533,0.088265,-0.241205,0.208174,-0.000866
1,-0.124818,0.193649,0.114702,0.073776,0.070586,-0.428048,0.175881,0.413512,-0.242877,-0.143062,...,0.301777,0.138119,0.004045,0.028687,0.387577,0.166698,0.075562,-0.220428,0.186534,-0.008372
2,-0.145434,0.242344,0.150249,0.094402,0.064572,-0.529680,0.219038,0.459892,-0.292647,-0.204233,...,0.334887,0.168496,0.006037,0.011837,0.458752,0.184049,0.036297,-0.272599,0.230403,0.018444
3,-0.187611,0.295479,0.172522,0.118448,0.107155,-0.667121,0.281685,0.640442,-0.382094,-0.223745,...,0.463472,0.217598,0.005784,0.060520,0.605767,0.270063,0.129859,-0.337651,0.280579,-0.010142
4,-0.165033,0.245939,0.155559,0.099222,0.097591,-0.567162,0.241314,0.548204,-0.327811,-0.200063,...,0.400228,0.182194,0.014255,0.053182,0.518166,0.233495,0.105921,-0.293684,0.235004,-0.008302
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5564,-0.157182,0.281277,0.182277,0.110121,0.083705,-0.601472,0.268662,0.549523,-0.340312,-0.224017,...,0.401021,0.201000,0.018156,0.027529,0.550636,0.220398,0.067185,-0.300903,0.258411,0.019089
5565,-0.171342,0.257806,0.162842,0.106645,0.096680,-0.603680,0.251819,0.562289,-0.347134,-0.207584,...,0.413842,0.193587,-0.000949,0.039250,0.541348,0.237355,0.084560,-0.312524,0.253324,0.001852
5566,-0.187139,0.300356,0.177230,0.111188,0.096724,-0.661415,0.289031,0.638571,-0.379190,-0.236314,...,0.467128,0.230370,0.019696,0.069834,0.615487,0.269439,0.131143,-0.320957,0.273181,-0.002512
5567,-0.167542,0.270487,0.162837,0.106601,0.090849,-0.603800,0.257959,0.571864,-0.341278,-0.219991,...,0.412463,0.201742,0.020572,0.051879,0.553949,0.240224,0.098957,-0.296325,0.247860,-0.005775
5568,-0.194470,0.282665,0.177579,0.114341,0.106240,-0.660041,0.273774,0.621961,-0.370941,-0.238347,...,0.449718,0.212788,0.017701,0.053959,0.597294,0.266838,0.109425,-0.329859,0.265506,-0.005778

In [171]:
df.shape

(5569, 100)

In [172]:
# Independent feature
X=df
X.shape

(5569, 100)

In [173]:
#dependent features
y.shape

(5569,)

In [174]:
X.isnull().sum()

0     12
1     12
2     12
3     12
4     12
      ..
95    12
96    12
97    12
98    12
99    12
Length: 100, dtype: int64

In [175]:
df['output']=y

In [176]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,output
0,-0.131063,0.222093,0.133460,0.084605,0.074154,-0.490187,0.217660,0.470295,-0.278467,-0.172696,...,0.167039,0.012663,0.042663,0.458498,0.196533,0.088265,-0.241205,0.208174,-0.000866,1
1,-0.124818,0.193649,0.114702,0.073776,0.070586,-0.428048,0.175881,0.413512,-0.242877,-0.143062,...,0.138119,0.004045,0.028687,0.387577,0.166698,0.075562,-0.220428,0.186534,-0.008372,1
2,-0.145434,0.242344,0.150249,0.094402,0.064572,-0.529680,0.219038,0.459892,-0.292647,-0.204233,...,0.168496,0.006037,0.011837,0.458752,0.184049,0.036297,-0.272599,0.230403,0.018444,0
3,-0.187611,0.295479,0.172522,0.118448,0.107155,-0.667121,0.281685,0.640442,-0.382094,-0.223745,...,0.217598,0.005784,0.060520,0.605767,0.270063,0.129859,-0.337651,0.280579,-0.010142,1
4,-0.165033,0.245939,0.155559,0.099222,0.097591,-0.567162,0.241314,0.548204,-0.327811,-0.200063,...,0.182194,0.014255,0.053182,0.518166,0.233495,0.105921,-0.293684,0.235004,-0.008302,1

In [177]:
df.dropna(inplace=True)

In [178]:
X.isnull().sum()

0         0
1         0
2         0
3         0
4         0
         ..
96        0
97        0
98        0
99        0
output    0
Length: 101, dtype: int64

In [179]:
y=df['output']
y

0       1
1       1
2       0
3       1
4       1
       ..
5564    0
5565    1
5566    1
5567    1
5568    1
Name: output, Length: 5557, dtype: int64

In [180]:
X = df.drop('output', axis=1)
X.shape

(5557, 100)

In [181]:
## Train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [182]:
X_train.shape

(4445, 100)

In [183]:
len(y_train)

4445

In [184]:
# Applying RandomForest Classifer
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()

In [185]:
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [186]:
y_pred=classifier.predict(X_test)

In [187]:
from sklearn.metrics import accuracy_score, classification_report
print(accuracy_score(y_test,y_pred))

0.9721223021582733

In [188]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.91      0.88      0.89       144
           1       0.98      0.99      0.98       968

    accuracy                           0.97      1112
   macro avg       0.94      0.93      0.94      1112
weighted avg       0.97      0.97      0.97      1112